### BONJOUR SIMON, ICI JEAN-HUGUES ROY
### TOUS MES COMMENTAIRES SERONT EN MAJUSCULES ET PRÉCÉDÉS DE 3 # (HASHTAGS)

variable = list(range(20000,30151)) ### EXCELLENT DÉPART!

for kobe in variable: ### RIP KOBE BRYANT!! ON PEUT EFFECTIVEMENT RENDRE DES HOMMAGES DANS SES NOMS DE VARIABLES!
    print("https://montrealcampus.ca/?p=" + str(kobe))

print(len(variable))

### TA PREMIÈRE PARTIE, CI-DESSUS, FONCTIONNE BIEN.
### TA SECONDE PARTIE, CI-DESSOUS, AJOUTE LA LISTE "l2" QUI MANQUAIT. C'EST PARFAIT!

l2 = []
for kobe in variable:
    l2.append("https://montrealcampus.ca/?p=" + str(kobe))
    # print(l2) ### ICI, TU IMPRIMES LE CONTENU DE LA LISTE 10150 FOIS, ET ELLE CONTIENT PROGRESSIVEMENT DE PLUS EN PLUS D'ÉLÉMENTS, CE QUI FAIT QUE C'EST HYPER LONG... ET INUTILE. FAIS CE "PRINT" À L'EXTÉRIEUR DE TA BOUCLE, APRÈS:

print(l2)

### PUIS, POUR VÉRIFIER SI ON A LE NOMBRE D'URLS QU'IL FAUT:

print(len(l2))

### TRÈS BIEN, DONC, TU ÉTAIS TOUT PRÈS DU BUT!
### NE MANQUAIENT QUE QUELQUES COMMENTAIRES DANS TON CODE POUR M'EXPLIQUER CE QUE TU AS FAIT OU TENTÉ DE FAIRE. :)